/**
 * The `BiometricDevicePort` (HRM §11.1, HR-20) — the hexagonal boundary between the
 * attendance engine and whatever is bolted to the turnstile.
 *
 * The point of the port is sequencing, not abstraction for its own sake. Real ZKTeco /
 * eSSL / Matrix SDK integration is post-MVP, but the CONTRACT is fixed now: idempotent
 * ingest keyed on (tenant, device, employee, timestamp), a client-generated
 * `clientPunchId` so an offline kiosk can queue-and-forward, and a poll window rather
 * than a push assumption. The demo runs a deterministic fake adapter through exactly the
 * same interface, so the day the real bridge lands, nothing above this line changes.
 */
export const BIOMETRIC_DEVICE = Symbol("BiometricDevice");

export interface DevicePunch {
  deviceId: string;
  empCode: string;
  /** ISO-8601 instant. Server-side clock must be NTP-traceable (NFR-11, CERT-In). */
  punchTime: string;
  direction: "in" | "out" | "auto";
  source: "device" | "csv" | "mobile" | "web" | "manual";
  /** Generated by the CLIENT (UUIDv7) so a store-and-forward batch survives replay. */
  clientPunchId?: string;
}

export interface BiometricDevice {
  /** Which adapter answered — surfaced in the ingest response so a demo is never mistaken for a device. */
  readonly adapterName: string;
  /**
   * Pull every punch the device holds for a window. Callers must assume AT-LEAST-ONCE
   * delivery: the same punch may be returned by two polls, and the ingest path dedupes it.
   */
  poll(fromIso: string, toIso: string): Promise<DevicePunch[]>;
}
