import type { DemoScenario } from "./demo-scenarios";

/**
 * Long-form presenter journeys. Like the focused scenarios, these contain narration only:
 * they do not seed records, call APIs or simulate a successful write. Each step opens an
 * existing XELOR screen and explains where governed automation would operate in production.
 */
export const fullScaleDemoScenarios: DemoScenario[] = [
  {
    id: "manual-order-to-cash",
    title: "From paper and phone orders to cash",
    category: "Full business transformation",
    severity: "High",
    duration: "18–22 min",
    problem: "A growing manufacturer runs daily reporting in notebooks and spreadsheets. A customer order arrives by phone, is written on paper and must be carried manually through purchasing, production, delivery, invoicing and collections.",
    decision: "Show how XELOR digitises the business without losing human control or disrupting today's operations.",
    outcome: "One traceable digital journey from handwritten input to fulfilled order, collected cash and live management reporting.",
    icon: "Route",
    accent: "#4a1f3f",
    scale: "full",
    demoRecord: {
      reference: "DEMO-JOURNEY-2407",
      subject: "Apex Mobility · phone order to cash",
      facts: [
        { label: "Customer note", value: "120 PX-400 assemblies by 04-Aug-2026" },
        { label: "OCR confidence", value: "94% overall · quantity needs review" },
        { label: "Order value", value: "₹18.60 L · fictional" },
      ],
    },
    steps: [
      { phase: "Discover", title: "Understand today's manual work", path: "/integration/flows", body: "We begin with a fictional company where shift output, stock and orders are recorded in notebooks, spreadsheet files and chat messages. ONYX maps each hand-off, duplicate entry and delay before proposing any automation.", presenterLine: "Digital transformation starts by understanding the real work—not by forcing a new screen onto people.", agents: ["ONYX", "HEXA"] },
      { phase: "Capture", title: "Collect paper and spreadsheet reports", path: "/aiops/connectors", body: "Photos of paper sheets, PDFs, spreadsheets and mailbox attachments enter a controlled document intake. Every file keeps its source, time and uploader; the demo does not upload a real document.", presenterLine: "Old and new ways of working can coexist during the transition.", agents: ["ONYX", "HEXA"] },
      { phase: "Digitise", title: "OCR turns documents into proposed data", path: "/aiops/registry", body: "Document AI extracts dates, item codes, quantities, customer names and totals. Confidence is stored per field, and the original image remains beside the proposed values.", presenterLine: "OCR proposes structured data; it never makes uncertain handwriting silently become business truth.", agents: ["ONYX", "MICA"] },
      { phase: "Validate", title: "A person checks uncertain fields", path: "/aiops/review", body: "Low-confidence values, duplicate documents and master-data mismatches go to a simple side-by-side review. A trained person corrects only the highlighted fields and the correction becomes auditable feedback.", presenterLine: "The human reviews exceptions, not every character on every page.", agents: ["HEXA", "Human reviewer"] },
      { phase: "Capture", title: "A customer places an order by phone", path: "/copilot/ask", body: "In the fictional story, a salesperson photographs their handwritten call note or dictates the order. ONYX extracts the customer, product, quantity, requested date and special instructions as a draft—not a confirmed order.", presenterLine: "The salesperson can work naturally while XELOR creates a structured draft in the background.", agents: ["ONYX", "MICA"] },
      { phase: "Validate", title: "Match the customer and commercial terms", path: "/sales/customers", body: "MICA matches the draft to the customer master, delivery address, credit context and agreed terms. Ambiguous matches remain visibly unresolved for a person.", presenterLine: "The platform connects the note to trusted master data before it becomes a transaction.", agents: ["MICA", "RASP"] },
      { phase: "Human decision", title: "Confirm the sales order", path: "/sales/orders", body: "The salesperson sees the original note beside the clean order draft and confirms product, quantity, price and requested date. In this presentation, no order is created or changed.", presenterLine: "AI removes retyping, but the responsible salesperson confirms the customer promise.", agents: ["MICA", "Human salesperson"] },
      { phase: "Calculate", title: "Check what can be promised", path: "/inventory/stock", body: "SPAR checks usable, reserved, incoming and quality-held stock. Deterministic available-to-promise rules calculate the gap; AI explains it in simple language.", presenterLine: "Inventory rules calculate the quantity. AI explains what is available and why.", agents: ["SPAR", "KILN"] },
      { phase: "Calculate", title: "Plan materials and capacity", path: "/planning/mrp", body: "AXLE expands the bill of material, lead times and production capacity. It produces planned supply and exceptions for missing components rather than inventing a feasible date.", presenterLine: "The planning engine creates the facts; agents coordinate the response across teams.", agents: ["AXLE", "SPAR"] },
      { phase: "Coordinate", title: "Prepare purchase requirements", path: "/purchase/orders", body: "SPAR groups shortages into proposed purchase orders using approved vendors, minimum quantities, prices and lead times. ONYX attaches the customer and production consequences to each proposal.", presenterLine: "The buyer sees why each purchase is needed, not just another line in a queue.", agents: ["SPAR", "ONYX", "RASP"] },
      { phase: "Govern", title: "Approve spend before sending a PO", path: "/agentos/approvals", body: "HEXA routes the precise purchase proposal to the person with the correct spending authority and requires a note. Demo Mode cannot approve or send the fictional PO.", presenterLine: "Automation prepares the work; authority remains with the accountable person.", agents: ["HEXA", "Human approver"] },
      { phase: "Execute", title: "Receive and identify the material", path: "/purchase/grn", body: "When material arrives, a warehouse worker would scan the PO and quantity on a phone. XELOR links the receipt to the supplier, order and batch while handling shortages or over-delivery as exceptions.", presenterLine: "The physical material and its digital identity meet at receiving.", agents: ["SPAR"] },
      { phase: "Verify", title: "Inspect before release", path: "/quality/inspections", body: "KILN selects the required inspection plan, captures results and keeps failed or uncertain material unavailable. Release requires the correct quality authority.", presenterLine: "Received does not automatically mean usable.", agents: ["KILN", "HEXA"] },
      { phase: "Execute", title: "Run production from the same plan", path: "/production/orders", body: "AXLE shows the production order, required operations and material readiness. Shop-floor progress updates replace the old handwritten shift report while exceptions still work if connectivity is lost.", presenterLine: "The original customer need now drives a traceable factory plan.", agents: ["AXLE", "KILN"] },
      { phase: "Verify", title: "Move finished goods to dispatch", path: "/inventory/warehouses", body: "SPAR verifies finished quantity, batch identity, storage location and customer allocation before dispatch. The order retains end-to-end material traceability.", presenterLine: "At any point, we can explain where the order and its material came from.", agents: ["SPAR", "MICA"] },
      { phase: "Execute", title: "Create the financial record", path: "/accounts/vouchers", body: "The fulfilled order becomes the basis for an invoice and accounting voucher through deterministic posting rules. RASP checks totals, taxes, terms and duplicate risk; Demo Mode posts nothing.", presenterLine: "Operational completion flows into finance without somebody typing the same order again.", agents: ["RASP", "HEXA"] },
      { phase: "Verify", title: "Follow the money in", path: "/working-capital/money-in", body: "RASP tracks invoice due dates, expected receipts and collection risk. MICA gives the customer team a prioritized, evidence-based follow-up rather than a generic reminder list.", presenterLine: "The story does not end at dispatch—it ends when value returns as cash.", agents: ["RASP", "MICA"] },
      { phase: "Close", title: "Management sees one live report", path: "/working-capital/finance-pack", body: "The original manual reports are replaced by a concise live view of order status, purchasing, production, quality, margin and cash. Every figure can be traced back to its source transaction and responsible person.", presenterLine: "One customer phone call is now visible from first note to final cash—without losing the evidence behind it.", agents: ["ONYX", "RASP", "HEXA"] },
    ],
  },
  {
    id: "drawing-to-first-delivery",
    title: "From customer drawing to first delivery",
    category: "Full new-product journey",
    severity: "Medium",
    duration: "16–20 min",
    problem: "A new customer emails a drawing and asks for 2,000 custom assemblies. Engineering, sales, purchasing, quality and production currently re-enter the same details in separate files.",
    decision: "Turn an unstructured request into a controlled product, feasible promise and profitable first delivery.",
    outcome: "A governed digital thread from drawing and BOM through sourcing, inspection, production, invoice and margin review.",
    icon: "DraftingCompass",
    accent: "#0e3a62",
    scale: "full",
    demoRecord: {
      reference: "DEMO-NPI-2000",
      subject: "New custom assembly · first delivery",
      facts: [
        { label: "Request", value: "2,000 custom assemblies" },
        { label: "Source", value: "Customer email and drawing rev A" },
        { label: "Control", value: "Engineering release required" },
      ],
    },
    steps: [
      { phase: "Capture", title: "Receive the drawing and request", path: "/integration/flows", body: "A fictional customer email, PDF drawing and quantity request enter one controlled intake with source and version preserved.", presenterLine: "We capture the customer request once and carry its identity through the whole company.", agents: ["ONYX", "MICA"] },
      { phase: "Digitise", title: "Extract requirements from the drawing", path: "/aiops/registry", body: "Document AI proposes part numbers, dimensions, materials, tolerances and requested quantities with field-level confidence and drawing references.", presenterLine: "AI accelerates reading; engineering remains responsible for interpretation.", agents: ["ONYX", "AXLE"] },
      { phase: "Human decision", title: "Engineer validates the item", path: "/engineering/items", body: "An engineer reviews uncertain requirements, creates the controlled item definition and records assumptions. Demo Mode only displays the workspace.", presenterLine: "The model can suggest; only engineering can release the definition.", agents: ["AXLE", "Human engineer"] },
      { phase: "Calculate", title: "Build and check the BOM", path: "/engineering/bom", body: "AXLE structures the proposed components and validates quantities, revisions and missing specifications.", presenterLine: "Every downstream plan now uses one governed product structure.", agents: ["AXLE", "KILN"] },
      { phase: "Govern", title: "Define quality evidence", path: "/quality/documents", body: "KILN connects inspection plans, certificates and controlled instructions to the product revision.", presenterLine: "Quality requirements are designed in before purchasing begins.", agents: ["KILN", "HEXA"] },
      { phase: "Calculate", title: "Test price and margin", path: "/working-capital/margins", body: "RASP models material, conversion, inspection and working-capital costs so sales can see a defensible margin range.", presenterLine: "The commercial promise is tested against real operating cost.", agents: ["RASP", "MICA"] },
      { phase: "Human decision", title: "Confirm the customer order", path: "/sales/orders", body: "MICA prepares the clean order and promise assumptions for a salesperson to review. The fictional order remains unsubmitted.", presenterLine: "A human owns the price and promise; the evidence is already assembled.", agents: ["MICA", "Human salesperson"] },
      { phase: "Calculate", title: "Generate the material plan", path: "/planning/mrp", body: "Planning rules calculate component need, lead-time exposure and production capacity for the first batch.", presenterLine: "Feasibility is calculated before a date is committed.", agents: ["AXLE", "SPAR"] },
      { phase: "Investigate", title: "Compare approved suppliers", path: "/purchase/vendors", body: "SPAR compares approved sources, price, lead time, quality history and dependency risk.", presenterLine: "The buyer sees more than the lowest price.", agents: ["SPAR", "KILN", "RASP"] },
      { phase: "Coordinate", title: "Prepare sourcing and production", path: "/purchase/orders", body: "ONYX joins purchase proposals, capacity and customer consequence into one coordinated launch plan.", presenterLine: "Departments act from one plan instead of exchanging disconnected spreadsheets.", agents: ["ONYX", "SPAR", "AXLE"] },
      { phase: "Govern", title: "Approve the launch commitments", path: "/agentos/approvals", body: "HEXA separates commercial, engineering and spending decisions and routes each to the right authority. No demo approval is submitted.", presenterLine: "One workflow can contain several decisions without creating one dangerous blanket approval.", agents: ["HEXA", "Human approvers"] },
      { phase: "Execute", title: "Receive the first material", path: "/purchase/grn", body: "The warehouse would scan the receipt against the approved PO, creating batch identity and supplier traceability.", presenterLine: "The digital thread reaches the first physical hand-off.", agents: ["SPAR"] },
      { phase: "Verify", title: "Run first-article inspection", path: "/quality/inspections", body: "KILN presents the correct revision and inspection plan and keeps results attached to the material and product batch.", presenterLine: "The first product is proven against the same requirements the customer sent.", agents: ["KILN", "AXLE"] },
      { phase: "Execute", title: "Produce the first batch", path: "/production/orders", body: "AXLE coordinates material readiness, operations and exception handling for the controlled first run.", presenterLine: "Production works from the released item, BOM and quality plan.", agents: ["AXLE", "KILN"] },
      { phase: "Verify", title: "Trace the finished stock", path: "/inventory/stock", body: "SPAR confirms the saleable quantity, batch and allocation to the customer order.", presenterLine: "The finished unit keeps its complete ancestry.", agents: ["SPAR", "MICA"] },
      { phase: "Close", title: "Review delivery, cash and margin", path: "/working-capital/finance-pack", body: "RASP closes the journey with actual-versus-planned margin, cash timing and lessons for the repeat order.", presenterLine: "The first delivery becomes evidence that improves the next commercial decision.", agents: ["RASP", "ONYX"] },
    ],
  },
  {
    id: "factory-control-tower",
    title: "Run a full factory crisis response",
    category: "Full control-tower journey",
    severity: "Urgent",
    duration: "18–22 min",
    problem: "On the same morning, a priority order increases, a supplier slips, a machine fails and replacement material fails inspection. Leaders need one coordinated response—not four separate alerts.",
    decision: "Protect people, customer promises, margin and cash while restoring stable operations.",
    outcome: "A cross-functional recovery mission with evidence, controlled approvals, reversible actions and verified closure.",
    icon: "RadioTower",
    accent: "#9b1d3f",
    scale: "full",
    demoRecord: {
      reference: "DEMO-CRISIS-0731",
      subject: "Priority delivery recovery",
      facts: [
        { label: "Customer", value: "Apex Mobility · DEMO-SO-1048" },
        { label: "Signals", value: "Demand, supplier, machine and quality" },
        { label: "Control", value: "4 separate human approvals" },
      ],
    },
    steps: [
      { phase: "Trigger", title: "Four signals become one mission", path: "/agentos/command", body: "ONYX correlates fictional demand, supply, machine and quality events into one bounded recovery mission instead of creating competing departmental responses.", presenterLine: "The control tower recognizes one business problem behind four alarms.", agents: ["ONYX", "HEXA"] },
      { phase: "Investigate", title: "Confirm the customer consequence", path: "/sales/orders", body: "MICA identifies affected promises, priority and customer context without sending any message.", presenterLine: "We begin with the outcome the customer will feel.", agents: ["MICA"] },
      { phase: "Investigate", title: "Measure the supplier delay", path: "/purchase/orders", body: "SPAR traces the delayed PO to material demand, approved substitutes and alternate suppliers.", presenterLine: "Supply impact is tied directly to the orders it threatens.", agents: ["SPAR"] },
      { phase: "Investigate", title: "Understand the machine failure", path: "/maintenance/downtime", body: "AXLE checks asset history, repair estimate, alternate capacity and safety constraints.", presenterLine: "Maintenance is part of the business recovery, not a separate ticket.", agents: ["AXLE", "HEXA"] },
      { phase: "Investigate", title: "Contain failed material", path: "/quality/findings", body: "KILN identifies every location and order connected to the held batch and keeps it out of usable supply.", presenterLine: "Containment happens before optimization.", agents: ["KILN", "SPAR"] },
      { phase: "Calculate", title: "Recalculate available supply", path: "/inventory/stock", body: "Inventory rules separate usable, reserved, held and incoming stock across locations.", presenterLine: "Only verified usable material enters the recovery plan.", agents: ["SPAR", "KILN"] },
      { phase: "Calculate", title: "Rebuild the feasible schedule", path: "/planning/exceptions", body: "AXLE propagates the combined material and capacity constraints into dates and order exceptions.", presenterLine: "The planning engine shows what is feasible under the new reality.", agents: ["AXLE"] },
      { phase: "Coordinate", title: "Compare recovery scenarios", path: "/working-capital/scenarios", body: "ONYX assembles expedite, alternate-source, overtime, resequence and partial-delivery options. RASP adds cost, cash and margin consequences.", presenterLine: "Leadership sees complete choices, not isolated departmental recommendations.", agents: ["ONYX", "RASP", "MICA", "SPAR", "AXLE"] },
      { phase: "Govern", title: "Test safety and policy", path: "/administration/roles", body: "HEXA checks who may approve overtime, alternate sourcing, customer commitments and quality disposition, preserving segregation of duties.", presenterLine: "Urgency does not erase authority or safety controls.", agents: ["HEXA"] },
      { phase: "Human decision", title: "Approve exact recovery actions", path: "/agentos/approvals", body: "Named leaders would approve each precise action with evidence and a note. Demo Mode cannot submit any decision.", presenterLine: "People approve consequences they can understand—not a vague request to let AI fix it.", agents: ["HEXA", "Human approvers"] },
      { phase: "Execute", title: "Prepare alternate supply", path: "/purchase/vendors", body: "SPAR would issue only approved sourcing actions after authority is verified, with rollback or cancellation conditions where possible.", presenterLine: "Execution begins with controlled and reversible actions.", agents: ["SPAR", "HEXA"] },
      { phase: "Execute", title: "Resequence production", path: "/production/orders", body: "AXLE would apply the approved sequence while protecting locked work and recording every change.", presenterLine: "The approved plan becomes visible operational work.", agents: ["AXLE"] },
      { phase: "Execute", title: "Open corrective action", path: "/quality/corrective-actions", body: "KILN separates immediate containment from supplier root cause and preventive work.", presenterLine: "Recovery fixes today while corrective action reduces recurrence.", agents: ["KILN", "SPAR"] },
      { phase: "Verify", title: "Prove the new plan worked", path: "/agentos/command", body: "ONYX checks postconditions: material confirmed, machine plan active, quality hold respected and customer date recalculated. Idempotency prevents duplicate execution.", presenterLine: "The mission verifies the result instead of assuming a successful click means success.", agents: ["ONYX", "HEXA"] },
      { phase: "Close", title: "Communicate and record the outcome", path: "/copilot/ask", body: "MICA drafts plain-language updates for customers and teams from verified facts. A person reviews any external message.", presenterLine: "Everyone receives one consistent explanation grounded in the final plan.", agents: ["MICA", "Human reviewer"] },
      { phase: "Close", title: "Learn from the complete audit trail", path: "/administration/audit", body: "HEXA closes the fictional mission with triggers, evidence, recommendations, decisions, actions and verification linked in one timeline.", presenterLine: "The crisis becomes an auditable lesson, not just a collection of messages.", agents: ["HEXA", "ONYX"] },
    ],
  },
];
