"use client";
import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowDown, ArrowUp, Check, Save, Settings2 } from "lucide-react";
import { useAccess } from "../access/permissions";
import { AppError } from "../api/errors";
import { useErpWorkspace } from "./workspace-context";
import { DEFAULT_CONFIG, DEPARTMENTS, INDUSTRIES, actionLabel, type DepartmentKey, type WorkspaceConfig } from "./workspace-model";

export function ErpConfigure(): React.JSX.Element {
  const { can } = useAccess();
  const { config, updatedAt, loading, error, save, actions } = useErpWorkspace();
  const [draft,setDraft]=useState<WorkspaceConfig>(config);
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null); const [failure,setFailure]=useState<string|null>(null);
  const canWrite=can("admin.settings.write")&&can("general.company.read");
  useEffect(()=>{setDraft(config);},[config]);
  const changed=JSON.stringify(config)!==JSON.stringify(draft);
  const reorder=(id:string,delta:number):void=>{setDraft(previous=>{const order=[...previous.quickActionOrder];const index=order.indexOf(id);const target=index+delta;if(index<0||target<0||target>=order.length)return previous;[order[index],order[target]]=[order[target]!,order[index]!];return {...previous,quickActionOrder:order};});};
  const submit=async(event:FormEvent):Promise<void>=>{event.preventDefault();if(!canWrite||saving||loading||error)return;setSaving(true);setFailure(null);setMessage(null);try{await save(draft);setMessage("Workspace saved for your company. Navigation and shortcuts have been updated.");}catch(reason){setFailure(reason instanceof AppError?reason.message:"The settings could not be saved. Your changes remain here so you can retry.");}finally{setSaving(false);}};
  return <div><div className="erp2-page-heading"><div><p className="erp2-eyebrow">COMPANY WORKSPACE SETTINGS</p><h1>Make XELOR fit your day.</h1><p>Choose the language, starting points and workspaces your business uses.</p></div><span className="erp2-pill"><Settings2 className="h-3 w-3" aria-hidden />{updatedAt?"Company layout saved":"Standard layout"}</span></div><div className="erp2-config-explanation"><strong>Your workspace, configured together.</strong><p>These settings are saved for this company. Industry presets arrange navigation, terminology and shortcuts; they do not change accounting rules, approval limits, inventory behaviour or access permissions.</p></div>{!canWrite?<div className="erp2-notice"><span>You can review the layout. A company administrator with settings access is needed to save changes.</span>{can("admin.access.read")?<Link href="/administration/roles">Review access</Link>:null}</div>:null}
    <form onSubmit={event=>void submit(event)}><fieldset disabled={!canWrite||loading||saving||Boolean(error)} className="erp2-settings-fieldset"><section className="erp2-settings-section"><div><span className="erp2-setting-step">01</span><h2>Start with your business</h2><p>Choose a starting layout, then adjust it below.</p></div><div className="erp2-settings-content"><label className="erp2-field"><span>Workspace name</span><input value={draft.businessLabel} onChange={event=>setDraft(previous=>({...previous,businessLabel:event.target.value}))} maxLength={80} placeholder="Use the company name" /><small>A display label only. Legal company records stay in Company records.</small></label><div className="erp2-preset-grid" role="group" aria-label="Industry workspace preset">{INDUSTRIES.map(preset=><button key={preset.id} type="button" aria-pressed={draft.industryPreset===preset.id} onClick={()=>{setMessage(null);setDraft(previous=>({...previous,industryPreset:preset.id,terminology:{...preset.terminology},visibleDepartments:[...preset.departments],quickActionOrder:[...preset.actions]}));}}><span>{draft.industryPreset===preset.id?<Check className="h-4 w-4" aria-hidden />:null}</span><strong>{preset.name}</strong><small>{preset.description}</small></button>)}</div><p className="erp2-field-note">These are workspace presets for existing ERP capabilities. Process, regulated and other specialist requirements need their own workflow design.</p></div></section>
    <section className="erp2-settings-section"><div><span className="erp2-setting-step">02</span><h2>Use familiar names</h2><p>Apply your terminology to ERP navigation and shortcuts.</p></div><div className="erp2-settings-content erp2-terminology">{([['customer','Customers'],['supplier','Suppliers'],['item','Items'],['workOrder','Work orders']] as const).map(([key,label])=><label key={key} className="erp2-field"><span>{label}</span><input value={draft.terminology[key]} required maxLength={32} onChange={event=>setDraft(previous=>({...previous,terminology:{...previous.terminology,[key]:event.target.value}}))} /><small>Example: {key==='item'?'Parts or Products':key==='workOrder'?'Job orders or Build orders':key==='supplier'?'Vendors':'Clients'}</small></label>)}</div></section>
    <section className="erp2-settings-section"><div><span className="erp2-setting-step">03</span><h2>Choose visible workspaces</h2><p>Keep the main navigation focused. All permitted screens remain in All records.</p></div><div className="erp2-settings-content erp2-department-options">{DEPARTMENTS.filter(entry=>entry.key!=="company").map(department=><label key={department.key}><input type="checkbox" checked={draft.visibleDepartments.includes(department.key as DepartmentKey)} onChange={event=>setDraft(previous=>({...previous,visibleDepartments:event.target.checked?[...previous.visibleDepartments,department.key as DepartmentKey]:previous.visibleDepartments.filter(key=>key!==department.key)}))} /><span><strong>{department.label}</strong><small>{department.description}</small></span></label>)}<p className="erp2-field-note">Company setup and access settings always remain available to permitted users.</p></div></section>
    <section className="erp2-settings-section"><div><span className="erp2-setting-step">04</span><h2>Put useful tasks first</h2><p>Choose up to eight company shortcuts. Personal work focus fills the remaining places on the overview.</p></div><div className="erp2-settings-content"><div className="erp2-shortcut-options">{actions.map(action=><label key={action.id}><input type="checkbox" checked={draft.quickActionOrder.includes(action.id)} disabled={!draft.quickActionOrder.includes(action.id)&&draft.quickActionOrder.length>=8} onChange={event=>setDraft(previous=>({...previous,quickActionOrder:event.target.checked?[...previous.quickActionOrder,action.id]:previous.quickActionOrder.filter(id=>id!==action.id)}))} /><span>{actionLabel(action,draft)}</span></label>)}</div>{draft.quickActionOrder.length?<ol className="erp2-shortcut-order" aria-label="Shortcut order">{draft.quickActionOrder.map((id,index)=>{const action=actions.find(entry=>entry.id===id);return <li key={id}><span>{index+1}</span><strong>{action?actionLabel(action,draft):id}</strong><button type="button" disabled={index===0} onClick={()=>reorder(id,-1)} aria-label={`Move ${action?.label??id} earlier`}><ArrowUp className="h-3 w-3" aria-hidden /></button><button type="button" disabled={index===draft.quickActionOrder.length-1} onClick={()=>reorder(id,1)} aria-label={`Move ${action?.label??id} later`}><ArrowDown className="h-3 w-3" aria-hidden /></button></li>;})}</ol>:<p className="erp2-field-note">No company priorities selected. Each person sees the shortcuts for their chosen work focus.</p>}</div></section></fieldset>
    <div className="erp2-save-bar"><div>{message?<p className="erp2-save-success" role="status"><Check className="h-4 w-4" aria-hidden />{message}</p>:<p>{loading?"Loading company settings…":changed?"You have unsaved changes.":updatedAt?`Saved ${new Date(updatedAt).toLocaleString("en-IN")}`:"Using the standard company layout."}</p>}{failure?<p className="erp2-save-error" role="alert">{failure}</p>:null}</div><button type="button" className="btn btn-secondary" disabled={!canWrite||saving||loading||Boolean(error)} onClick={()=>{setDraft(structuredClone(DEFAULT_CONFIG));setMessage(null);}}>Use standard layout</button><button type="submit" className="btn btn-primary" disabled={!canWrite||!changed||saving||loading||Boolean(error)}><Save className="h-4 w-4" aria-hidden />{saving?"Saving…":"Save workspace"}</button></div></form>
  </div>;
}
