import type { ModuleManifest } from "@spine/registry/manifest";

export const workingCapitalManifest: ModuleManifest = {
  key: "working-capital",
  name: "Working Capital",
  summary: "See the cash tied up in customers, suppliers and stock—and what to do next.",
  department: "RASP",
  icon: "BadgeIndianRupee",
  licenceKey: "accounts",
  order: 71,
  nav: [
    {
      label: "Overview",
      path: "overview",
      permission: "accounts.ledger.read",
      icon: "LayoutDashboard",
      description: "A simple view of available cash, expected movement and the most important actions.",
    },
    {
      label: "Money in",
      path: "money-in",
      permission: "accounts.ledger.read",
      icon: "ArrowDownToLine",
      description: "Customer payments that are expected, late or need a follow-up.",
    },
    {
      label: "Money out",
      path: "money-out",
      permission: "accounts.ledger.read",
      icon: "ArrowUpFromLine",
      description: "Supplier payments coming up, with safe timing choices and no automatic payment.",
    },
    {
      label: "Stock & cash",
      path: "stock-cash",
      permission: "accounts.ledger.read",
      icon: "Boxes",
      description: "Stock that holds the most cash, including slow-moving material to review.",
    },
    {
      label: "Margins",
      path: "margins",
      permission: "accounts.ledger.read",
      icon: "ChartNoAxesCombined",
      description: "Which orders and product lines make or lose money, explained in simple words.",
    },
    {
      label: "Cash forecast",
      path: "cash-forecast",
      permission: "accounts.ledger.read",
      icon: "ChartSpline",
      description: "A 13-week cash outlook based on recorded orders, invoices, bills and stock plans.",
    },
    {
      label: "Scenarios",
      path: "scenarios",
      permission: "accounts.ledger.read",
      icon: "GitCompareArrows",
      description: "Compare safe what-if choices before anyone changes a real record or moves money.",
    },
    {
      label: "Finance pack",
      path: "finance-pack",
      permission: "accounts.ledger.read",
      icon: "FolderCheck",
      description: "A ready-to-review set of accounts, GST, bank and receivable records for a lender.",
    },
  ],
  screens: {
    overview: () => import("./screens/overview"),
    "money-in": () => import("./screens/money-in"),
    "money-out": () => import("./screens/money-out"),
    "stock-cash": () => import("./screens/stock-cash"),
    margins: () => import("./screens/margins"),
    "cash-forecast": () => import("./screens/cash-forecast"),
    scenarios: () => import("./screens/scenarios"),
    "finance-pack": () => import("./screens/finance-pack"),
  },
};
