"use client";

import { useState, type FormEvent } from "react";
import { ArrowDownToLine, Cable, Check, CircleCheck, Database, Eye, FileUp, LoaderCircle, Plus, RefreshCw, ShieldCheck, Unplug, X } from "lucide-react";
import { useQuery } from "@spine/data/use-query";
import { useAccess } from "@spine/access/permissions";
import { Modal } from "@spine/ui/modal";
import { mutate, readableError, type Connection, type ConnectorKind, type ConnectorType, type Snapshot } from "../api";

const LABELS: Record<ConnectorKind, string> = { native: "Factory ERP", odoo: "Odoo", tally: "Tally", sap: "SAP", vyapar: "Vyapar", generic: "Files / API" };
function date(value: string | null | undefined): string { return value ? new Date(value).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }) : "Not yet synced"; }

export default function ConnectionsScreen(): React.JSX.Element {
  const { can } = useAccess();
  const catalog = useQuery<{ data: ConnectorType[] }>("/connectivity/catalog");
  const connections = useQuery<{ data: Connection[] }>("/connectivity/connections");
  const [adding, setAdding] = useState<ConnectorKind | null>(null);
  const [importing, setImporting] = useState<Connection | null>(null);
  const [inspecting, setInspecting] = useState<Connection | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<{ text: string; error: boolean } | null>(null);
  const editable = can("integration.flow.manage");
  const rows = connections.data?.data ?? [];
  async function act(connection: Connection, operation: "test" | "sync"): Promise<void> {
    setBusy(`${connection.id}:${operation}`); setNotice(null);
    try {
      const result = await mutate<{ status?: string; detail?: string }>(`/connections/${connection.id}/${operation}`, {});
      setNotice({ text: operation === "test" ? result.detail ?? "Connection test completed." : `Evidence refreshed from ${connection.name}.`, error: result.status === "failed" });
      connections.reload();
    } catch (error) { setNotice({ text: readableError(error), error: true }); }
    finally { setBusy(null); }
  }
  return <div className="space-y-7">
    <div className="x-home-header mb-0"><div><p className="x-eyebrow mb-2">Data foundation</p><h1 className="x-page-heading">Your systems, connected.</h1><p className="x-page-description">Bring in the evidence you need. Keep your existing system in control.</p></div>{editable ? <button className="btn btn-primary" onClick={() => setAdding("native")}><Plus className="h-4 w-4" aria-hidden /><span>Add connection</span></button> : null}</div>
    <div className="x-notice"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" aria-hidden /><span>Connections read records into a dated snapshot. Refresh or import new evidence before making a time-sensitive decision.</span></div>
    {notice ? <div className="x-notice" data-tone={notice.error ? "error" : "info"} role="status"><span className="flex-1">{notice.text}</span><button onClick={() => setNotice(null)} aria-label="Dismiss message"><X className="h-4 w-4" /></button></div> : null}
    <section className="x-home-panel"><div className="x-home-panel-head"><div><h2 className="x-section-heading">Your connections</h2><p>{rows.length} configured {rows.length === 1 ? "source" : "sources"}</p></div><button className="x-icon-button" onClick={connections.reload} disabled={connections.loading} aria-label="Refresh connections"><RefreshCw className={`h-4 w-4 ${connections.loading ? "animate-spin" : ""}`} aria-hidden /></button></div>
      {connections.error ? <div className="x-notice m-5" data-tone="error">{readableError(connections.error)}</div> : connections.loading && !connections.data ? <div className="x-empty-state"><LoaderCircle className="h-7 w-7 animate-spin" aria-hidden /><p>Loading your connections…</p></div> : !rows.length ? <div className="x-empty-state"><Unplug className="h-9 w-9" aria-hidden /><h3>Your first connection starts here</h3><p>Connect the factory ERP, configure another system, or import a spreadsheet export.</p>{editable ? <button className="btn btn-primary mt-5" onClick={() => setAdding("native")}><Plus className="h-4 w-4" aria-hidden />Add a data source</button> : null}</div> : rows.map((connection) => <div key={connection.id} className="x-connection-row"><span className="x-connector-logo"><Database className="h-5 w-5" aria-hidden /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-[13px] font-semibold">{connection.name}</h3><span className={`chip ${connection.status === "connected" ? "chip-good" : connection.status === "failed" ? "chip-bad" : "chip-info"}`}>{connection.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-[10px] text-[var(--text-muted)]">{LABELS[connection.kind]} · {date(connection.lastSyncedAt)}</p>{connection.latestSnapshot ? <p className="mt-1 text-[11px] text-[var(--text-secondary)]">{connection.latestSnapshot.counts.orders} orders · {connection.latestSnapshot.counts.inventory} stock rows · {connection.latestSnapshot.counts.suppliers} suppliers</p> : <p className="mt-1 text-[11px] text-[var(--text-muted)]">No evidence received yet</p>}{connection.lastError ? <p className="mt-2 text-[11px] text-[var(--bad-ink)]">{connection.lastError}</p> : null}</div><div className="flex flex-wrap items-center gap-2">{connection.latestSnapshot ? <button className="btn btn-secondary btn-sm" onClick={() => setInspecting(connection)}><Eye className="h-3.5 w-3.5" aria-hidden />Evidence</button> : null}{editable ? <><button className="btn btn-secondary btn-sm" disabled={busy !== null} onClick={() => void act(connection, "test")}>{busy === `${connection.id}:test` ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" aria-hidden /> : <Cable className="h-3.5 w-3.5" aria-hidden />}Test</button>{["vyapar", "generic"].includes(connection.kind) ? <button className="btn btn-primary btn-sm" onClick={() => setImporting(connection)}><FileUp className="h-3.5 w-3.5" aria-hidden />Import file</button> : <button className="btn btn-primary btn-sm" disabled={busy !== null} onClick={() => void act(connection, "sync")}>{busy === `${connection.id}:sync` ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" aria-hidden /> : <RefreshCw className="h-3.5 w-3.5" aria-hidden />}Sync evidence</button>}</> : null}</div></div>)}
    </section>
    <section><div className="mb-4"><h2 className="x-section-heading">Connect a system</h2><p className="mt-1 text-[12px] text-[var(--text-muted)]">Choose the source that already holds your records.</p></div>{catalog.error ? <div className="x-notice" data-tone="error">{readableError(catalog.error)}</div> : <div className="x-connector-grid">{(catalog.data?.data ?? []).map((connector) => <article key={connector.kind} className="x-connector-card"><div className="flex items-center justify-between"><span className="x-connector-logo">{connector.name.slice(0, 2).toUpperCase()}</span><span className="chip chip-info">{connector.mode === "import" ? "File import" : "Read access"}</span></div><h3>{connector.name}</h3><p className="mb-5 flex-1">{connector.description}</p><button className="btn btn-secondary w-full" disabled={!editable} onClick={() => setAdding(connector.kind)}><Plus className="h-3.5 w-3.5" aria-hidden />Set up connection</button></article>)}</div>}</section>
    {adding ? <AddConnection kind={adding} types={catalog.data?.data ?? []} onClose={() => setAdding(null)} onSaved={() => { setAdding(null); connections.reload(); }} /> : null}
    {importing ? <ImportEvidence connection={importing} onClose={() => setImporting(null)} onSaved={() => { setImporting(null); connections.reload(); setNotice({ text: "File imported. The dated evidence is ready to review.", error: false }); }} /> : null}
    {inspecting ? <EvidenceView connection={inspecting} onClose={() => setInspecting(null)} /> : null}
  </div>;
}

function AddConnection({ kind: initial, types, onClose, onSaved }: { kind: ConnectorKind; types: ConnectorType[]; onClose: () => void; onSaved: () => void }): React.JSX.Element {
  const [kind, setKind] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault(); const values = new FormData(event.currentTarget); setBusy(true); setError(null);
    const field = (name: string): string | undefined => String(values.get(name) ?? "").trim() || undefined;
    try { await mutate("/connections", { kind, name: field("name"), baseUrl: field("baseUrl"), ...(field("apiKey") ? { credentials: { apiKey: field("apiKey") } } : {}), settings: { database: field("database"), company: field("company"), entityPath: field("entityPath"), entity: field("entity") } }); onSaved(); }
    catch (failure) { setError(readableError(failure)); } finally { setBusy(false); }
  }
  const remote = ["odoo", "sap", "tally"].includes(kind);
  return <Modal title="Add a connection" subtitle="Create a source, then test and sync its evidence." onClose={onClose} locked={busy} width="max-w-xl"><form onSubmit={(event) => void submit(event)} className="space-y-5"><div className="x-form-grid"><label className="x-field">System<select value={kind} onChange={(event) => setKind(event.target.value as ConnectorKind)}>{types.map((type) => <option key={type.kind} value={type.kind}>{type.name}</option>)}</select></label><label className="x-field">Connection name<input name="name" required maxLength={100} defaultValue={LABELS[initial]} placeholder="Coimbatore factory" data-autofocus /></label></div>{remote ? <label className="x-field">Server URL<input name="baseUrl" type="url" required placeholder="https://your-erp.example.com" /><small>Use the reachable address of the system you want to read.</small></label> : null}{kind === "odoo" ? <div className="x-form-grid"><label className="x-field">Database (optional)<input name="database" autoComplete="off" /></label><label className="x-field">Odoo API key<input name="apiKey" type="password" required autoComplete="new-password" /></label></div> : null}{kind === "tally" ? <label className="x-field">Company name<input name="company" placeholder="Company as named in Tally" /></label> : null}{kind === "sap" ? <div className="x-form-grid"><label className="x-field sm:col-span-2">OData entity path<input name="entityPath" required placeholder="/sap/opu/odata/sap/…" /></label><label className="x-field">Records<select name="entity"><option value="orders">Sales orders</option><option value="inventory">Inventory</option><option value="suppliers">Suppliers</option></select></label><label className="x-field">API key<input name="apiKey" type="password" autoComplete="new-password" /></label></div> : null}{kind === "native" ? <div className="x-notice"><CircleCheck className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />Reads orders, available stock and suppliers from this factory’s ERP, using your existing access.</div> : null}{["generic", "vyapar"].includes(kind) ? <div className="x-notice"><FileUp className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />After saving, import a CSV or JSON export. You will choose its record type and observation date.</div> : null}{error ? <div className="x-notice" data-tone="error" role="alert">{error}</div> : null}<div className="flex justify-end gap-2"><button className="btn btn-secondary" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="btn btn-primary" type="submit" disabled={busy}>{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Save connection</button></div></form></Modal>;
}

function ImportEvidence({ connection, onClose, onSaved }: { connection: Connection; onClose: () => void; onSaved: () => void }): React.JSX.Element {
  const [content, setContent] = useState(""); const [format, setFormat] = useState("csv"); const [fileName, setFileName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const values = new FormData(event.currentTarget); setBusy(true); setError(null); try { await mutate(`/connections/${connection.id}/import`, { format, content, entity: values.get("entity"), observedAt: new Date(`${String(values.get("observedAt"))}:00Z`).toISOString() }); onSaved(); } catch (failure) { setError(readableError(failure)); } finally { setBusy(false); } }
  return <Modal title="Import evidence" subtitle={connection.name} onClose={onClose} locked={busy}><form className="space-y-5" onSubmit={(event) => void submit(event)}><div className="x-form-grid"><label className="x-field">Format<select value={format} onChange={(event) => setFormat(event.target.value)}><option value="csv">CSV spreadsheet export</option><option value="json">JSON evidence bundle</option></select></label><label className="x-field">Record type<select name="entity"><option value="orders">Orders</option><option value="inventory">Inventory</option><option value="suppliers">Suppliers</option></select></label><label className="x-field">Evidence observed at (UTC)<input type="datetime-local" name="observedAt" required defaultValue={new Date().toISOString().slice(0, 16)} /></label><label className="x-field">Choose a file<input type="file" accept=".csv,.json,text/csv,application/json" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 1_000_000) { setError("Choose a file smaller than 1 MB."); return; } void file.text().then((text) => { setContent(text); setFileName(file.name); setFormat(file.name.toLowerCase().endsWith(".json") ? "json" : "csv"); setError(null); }); }} /></label></div><label className="x-field">Review file contents{fileName ? <small>{fileName}</small> : null}<textarea rows={8} required value={content} onChange={(event) => setContent(event.target.value)} placeholder={format === "csv" ? "itemCode,availableQty,uom" : '{"orders":[],"inventory":[],"suppliers":[]}'} className="font-mono" /><small>CSV columns: orders — externalId, itemCode, quantity, dueDate, unitPrice, currency; inventory — itemCode, availableQty, uom; suppliers — externalId, name, leadDays.</small></label>{error ? <div className="x-notice" data-tone="error" role="alert">{error}</div> : null}<div className="flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={onClose} disabled={busy}>Cancel</button><button className="btn btn-primary" type="submit" disabled={busy || !content.trim()}><ArrowDownToLine className="h-4 w-4" aria-hidden />{busy ? "Importing…" : "Import reviewed evidence"}</button></div></form></Modal>;
}

function EvidenceView({ connection, onClose }: { connection: Connection; onClose: () => void }): React.JSX.Element {
  const query = useQuery<{ data: Snapshot }>(`/connectivity/connections/${connection.id}/snapshot`); const data = query.data?.data;
  return <Modal title="Source evidence" subtitle={connection.name} onClose={onClose}>{query.error ? <div className="x-notice" data-tone="error">{readableError(query.error)}</div> : !data ? <p className="x-empty-copy">Reading evidence…</p> : <div className="space-y-5"><div className="x-notice"><Check className="mt-0.5 h-4 w-4 shrink-0" aria-hidden /><span>Observed {date(data.observedAt)} · Imported {date(data.importedAt)}<br />{data.counts.orders} orders · {data.counts.inventory} inventory rows · {data.counts.suppliers} suppliers</span></div>{data.warnings.map((warning, index) => <div key={index} className="x-notice" data-tone="warning">{warning}</div>)}{Object.entries(data.evidence).map(([entity, records]) => <div key={entity}><h3 className="x-section-heading capitalize">{entity}</h3><pre className="mt-3 max-h-52 overflow-auto rounded-lg border border-[var(--border-subtle)] bg-[var(--bg)] p-4 text-[11px]">{JSON.stringify(records.slice(0, 20), null, 2)}</pre>{records.length > 20 ? <p className="mt-2 text-[11px] text-[var(--text-muted)]">Showing the first 20 of {records.length} records.</p> : null}</div>)}</div>}</Modal>;
}
